using System.ComponentModel;
using System.Globalization;

namespace HandyControlDemo.Properties.Langs;

public class LangProvider : INotifyPropertyChanged
{
    private static readonly LangProvider InstanceField = new();

    public static LangProvider Instance => InstanceField;

    public static CultureInfo Culture
    {
        get => Lang.Culture;
        set
        {
            if (value == null || Equals(Lang.Culture, value))
            {
                return;
            }

            Lang.Culture = value;
            Instance.UpdateLangs();
        }
    }

    public static string GetLang(string key) =>
        Lang.ResourceManager.GetString(key, Lang.Culture) ?? key;

    public string About => Lang.About;
    public string AddItem => Lang.AddItem;
    public string AnimationPath => Lang.AnimationPath;
    public string AppClosingTip => Lang.AppClosingTip;
    public string Ask => Lang.Ask;
    public string AutoCompleteBox => Lang.AutoCompleteBox;
    public string Badge => Lang.Badge;
    public string BasicInfo => Lang.BasicInfo;
    public string BasicLayout => Lang.BasicLayout;
    public string Blink => Lang.Blink;
    public string Blog => Lang.Blog;
    public string Border => Lang.Border;
    public string Brush => Lang.Brush;
    public string Button => Lang.Button;
    public string ButtonCustom => Lang.ButtonCustom;
    public string ButtonGroup => Lang.ButtonGroup;
public string Calendar => Lang.Calendar;
    public string CalendarDatePicker => Lang.CalendarDatePicker;
    public string CalendarWithClock => Lang.CalendarWithClock;
    public string Card => Lang.Card;
    public string Carousel => Lang.Carousel;
    public string ChangeLangAsk => Lang.ChangeLangAsk;
    public string ChatBubble => Lang.ChatBubble;
    public string Chatroom => Lang.Chatroom;
    public string CheckBox => Lang.CheckBox;
    public string CheckComboBox => Lang.CheckComboBox;
    public string CirclePanel => Lang.CirclePanel;
    public string Clear => Lang.Clear;
    public string ConfettiCannon => Lang.ConfettiCannon;
    public string Content => Lang.Content;
    public string Click2Count => Lang.Click2Count;
    public string Clock => Lang.Clock;
    public string CloseMainWindowDialog => Lang.CloseMainWindowDialog;
    public string ColorPicker => Lang.ColorPicker;
    public string ColumnOffset => Lang.ColumnOffset;
    public string ColumnSpacing => Lang.ColumnSpacing;
    public string ComboBox => Lang.ComboBox;
    public string ComingSoon => Lang.ComingSoon;
    public string Comment => Lang.Comment;
    public string Common => Lang.Common;
    public string CompareSlider => Lang.CompareSlider;
    public string Complete => Lang.Complete;
    public string ContentDemoStr => Lang.ContentDemoStr;
    public string Contributors => Lang.Contributors;
    public string Controls => Lang.Controls;
    public string CoverFlow => Lang.CoverFlow;
    public string CoverView => Lang.CoverView;
    public string Danger => Lang.Danger;
    public string DataDisplay => Lang.DataDisplay;
    public string DataEntry => Lang.DataEntry;
    public string DataGrid => Lang.DataGrid;
    public string DatePicker => Lang.DatePicker;
    public string DateTimePicker => Lang.DateTimePicker;
    public string Default => Lang.Default;
    public string Demo => Lang.Demo;
    public string Dialog => Lang.Dialog;
    public string DialogDemo => Lang.DialogDemo;
    public string Divider => Lang.Divider;
    public string Doc_cn => Lang.Doc_cn;
    public string Doc_en => Lang.Doc_en;
public string Documentation => Lang.Documentation;
    public string DragHere => Lang.DragHere;
    public string Drawer => Lang.Drawer;
    public string DropDownButton => Lang.DropDownButton;
    public string Effects => Lang.Effects;
    public string ElementGroup => Lang.ElementGroup;
    public string Email => Lang.Email;
    public string Empty => Lang.Empty;
    public string Error => Lang.Error;
    public string Exit => Lang.Exit;
    public string Expander => Lang.Expander;
    public string Fatal => Lang.Fatal;
    public string Feedback => Lang.Feedback;
    public string FlexPanel => Lang.FlexPanel;
    public string FlipClock => Lang.FlipClock;
    public string FloatingBlock => Lang.FloatingBlock;
    public string FlowDocument => Lang.FlowDocument;
    public string FlowDocumentPageViewer => Lang.FlowDocumentPageViewer;
    public string FlowDocumentReader => Lang.FlowDocumentReader;
    public string FlowDocumentScrollViewer => Lang.FlowDocumentScrollViewer;
    public string Frame => Lang.Frame;
    public string Geometry => Lang.Geometry;
    public string GifImage => Lang.GifImage;
    public string GotoTop => Lang.GotoTop;
    public string Gravatar => Lang.Gravatar;
    public string Grid => Lang.Grid;
    public string GroupBox => Lang.GroupBox;
    public string Groups => Lang.Groups;
    public string Growl => Lang.Growl;
    public string GrowlAsk => Lang.GrowlAsk;
    public string GrowlDemo => Lang.GrowlDemo;
    public string GrowlError => Lang.GrowlError;
    public string GrowlFatal => Lang.GrowlFatal;
    public string GrowlInfo => Lang.GrowlInfo;
    public string GrowlSuccess => Lang.GrowlSuccess;
    public string GrowlWarning => Lang.GrowlWarning;
    public string HatchBrushGenerator => Lang.HatchBrushGenerator;
    public string HandyControl => Lang.HandyControl;
    public string HoneycombPanel => Lang.HoneycombPanel;
    public string HybridLayout => Lang.HybridLayout;
    public string HyperlinkButton => Lang.HyperlinkButton;
    public string Ignore => Lang.Ignore;
    public string ImageBlock => Lang.ImageBlock;
    public string ImageBrowser => Lang.ImageBrowser;
    public string ImageSelector => Lang.ImageSelector;
    public string ImageViewer => Lang.ImageViewer;
    public string Index => Lang.Index;
    public string Info => Lang.Info;
    public string Interacting => Lang.Interacting;
    public string InteractiveDialog => Lang.InteractiveDialog;
    public string IsNotPhone => Lang.IsNotPhone;
    public string Item1 => Lang.Item1;
    public string Item2 => Lang.Item2;
    public string Item3 => Lang.Item3;
    public string Label => Lang.Label;
    public string LangComment => Lang.LangComment;
    public string Layout => Lang.Layout;
    public string ListBox => Lang.ListBox;
    public string ListView => Lang.ListView;
    public string Loading => Lang.Loading;
    public string Magnifier => Lang.Magnifier;
public string Menu => Lang.Menu;
    public string MessageBox => Lang.MessageBox;
    public string MaskedTextBox => Lang.MaskedTextBox;
    public string Misc => Lang.Misc;
    public string MorphingAnimation => Lang.MorphingAnimation;
public string Name => Lang.Name;
    public string Navigation => Lang.Navigation;
    public string NoData => Lang.NoData;
    public string New => Lang.New;
    public string NewWindow => Lang.NewWindow;
    public string Next => Lang.Next;
    public string NextWeek => Lang.NextWeek;
    public string Notification => Lang.Notification;
    public string NotifyIcon => Lang.NotifyIcon;
    public string NumericUpDown => Lang.NumericUpDown;
    public string Off => Lang.Off;
    public string Ok => Lang.Ok;
    public string On => Lang.On;
    public string OpenBlurWindow => Lang.OpenBlurWindow;
    public string OpenCommonWindow => Lang.OpenCommonWindow;
    public string OpenCustomContentWindow => Lang.OpenCustomContentWindow;
    public string OpenCustomMessageWindow => Lang.OpenCustomMessageWindow;
    public string OpenCustomTitleBarWindow => Lang.OpenCustomTitleBarWindow;
    public string OpenGlowWindow => Lang.OpenGlowWindow;
    public string OpenImageBrowser => Lang.OpenImageBrowser;
    public string OpenMessageWindow => Lang.OpenMessageWindow;
    public string OpenMouseFollowWindow => Lang.OpenMouseFollowWindow;
    public string OpenNativeCommonWindow => Lang.OpenNativeCommonWindow;
    public string OpenNavigationWindow => Lang.OpenNavigationWindow;
    public string OpenNoCustomTitleBarDragableWindow => Lang.OpenNoCustomTitleBarDragableWindow;
    public string OpenPanel => Lang.OpenPanel;
    public string OpenSprite => Lang.OpenSprite;
    public string OpenTouchDragMoveWindow => Lang.OpenTouchDragMoveWindow;
    public string OptionA => Lang.OptionA;
    public string OptionB => Lang.OptionB;
    public string OutlineText => Lang.OutlineText;
    public string Pagination => Lang.Pagination;
    public string PasswordBox => Lang.PasswordBox;
    public string PinBox => Lang.PinBox;
    public string PleaseInput => Lang.PleaseInput;
    public string PleaseWait => Lang.PleaseWait;
    public string PlsEnterContent => Lang.PlsEnterContent;
    public string PlsEnterEmail => Lang.PlsEnterEmail;
    public string PlsEnterKey => Lang.PlsEnterKey;
    public string Poptip => Lang.Poptip;
    public string PoptipPositionStr => Lang.PoptipPositionStr;
    public string PracticalDemos => Lang.PracticalDemos;
    public string Prev => Lang.Prev;
    public string PreviewSlider => Lang.PreviewSlider;
    public string Primary => Lang.Primary;
    public string ProgressBar => Lang.ProgressBar;
    public string ProgressButton => Lang.ProgressButton;
    public string Project => Lang.Project;
    public string PropertyGrid => Lang.PropertyGrid;
    public string PushToTalk => Lang.PushToTalk;
    public string QQGroup => Lang.QQGroup;
    public string RadioButton => Lang.RadioButton;
    public string RangeSlider => Lang.RangeSlider;
public string Rate => Lang.Rate;
    public string Recommendation => Lang.Recommendation;
    public string Register => Lang.Register;
    public string RelativePanel => Lang.RelativePanel;
    public string Remark => Lang.Remark;
    public string RemoveItem => Lang.RemoveItem;
    public string RepeatButton => Lang.RepeatButton;
    public string Reply => Lang.Reply;
    public string Repository => Lang.Repository;
    public string ResponsiveLayout => Lang.ResponsiveLayout;
    public string Ribbon => Lang.Ribbon;
    public string RichTextBox => Lang.RichTextBox;
    public string RightClickHere => Lang.RightClickHere;
    public string RunningBlock => Lang.RunningBlock;
    public string Screenshot => Lang.Screenshot;
    public string ScrollViewer => Lang.ScrollViewer;
    public string SearchBar => Lang.SearchBar;
    public string Second => Lang.Second;
    public string Selected => Lang.Selected;
    public string SendNotification => Lang.SendNotification;
    public string Shield => Lang.Shield;
    public string ShowInCurrentWindow => Lang.ShowInCurrentWindow;
    public string ShowInMainWindow => Lang.ShowInMainWindow;
    public string ShowRowNumber => Lang.ShowRowNumber;
public string SideMenu => Lang.SideMenu;
    public string Slider => Lang.Slider;
    public string Small => Lang.Small;
    public string SplitButton => Lang.SplitButton;
    public string Sprite => Lang.Sprite;
    public string StartScreenshot => Lang.StartScreenshot;
    public string StaysOpen => Lang.StaysOpen;
    public string Step => Lang.Step;
    public string StepBar => Lang.StepBar;
    public string Styles => Lang.Styles;
    public string SubTitle => Lang.SubTitle;
    public string Success => Lang.Success;
    public string Switch => Lang.Switch;
    public string TabControl => Lang.TabControl;
    public string Tag => Lang.Tag;
    public string Text => Lang.Text;
    public string TextBlock => Lang.TextBlock;
    public string TextBox => Lang.TextBox;
    public string TextDialog => Lang.TextDialog;
    public string TextDialogInControl => Lang.TextDialogInControl;
    public string TextDialogWithTimer => Lang.TextDialogWithTimer;
    public string TimeBar => Lang.TimeBar;
    public string SelectedTime => Lang.SelectedTime;
    public string MouseWheelTip => Lang.MouseWheelTip;
    public string TimePicker => Lang.TimePicker;
    public string Tip => Lang.Tip;
    public string Title => Lang.Title;
    public string TitleDemoStr1 => Lang.TitleDemoStr1;
    public string TitleDemoStr2 => Lang.TitleDemoStr2;
    public string TitleDemoStr3 => Lang.TitleDemoStr3;
    public string Today => Lang.Today;
    public string ToggleButton => Lang.ToggleButton;
    public string ToggleSwitch => Lang.ToggleSwitch;
    public string Tomorrow => Lang.Tomorrow;
    public string ToolBar => Lang.ToolBar;
    public string Tools => Lang.Tools;
    public string Transfer => Lang.Transfer;
    public string TransitioningContentControl => Lang.TransitioningContentControl;
    public string TreeView => Lang.TreeView;
    public string Try2CloseApp => Lang.Try2CloseApp;
    public string Type => Lang.Type;
    public string UniformSpacingPanel => Lang.UniformSpacingPanel;
    public string UploadFile => Lang.UploadFile;
    public string UploadStr => Lang.UploadStr;
    public string Visibility => Lang.Visibility;
    public string Vsix => Lang.Vsix;
    public string Warning => Lang.Warning;
public string WaterfallPanel => Lang.WaterfallPanel;
    public string Watermark => Lang.Watermark;
    public string Website => Lang.Website;
    public string Window => Lang.Window;
    public string Close => Lang.Close;
    public string CustomTitleBarWindow => Lang.CustomTitleBarWindow;
    public string DragMe => Lang.DragMe;
    public string NotificationCardText => Lang.NotificationCardText;

    public string AddItem2 => Lang.AddItem2;
    public string AnotherSenderMessage => Lang.AnotherSenderMessage;
    public string Backlogs => Lang.Backlogs;
    public string BasicCannon => Lang.BasicCannon;
    public string Boards => Lang.Boards;
    public string BottomLeft => Lang.BottomLeft;
    public string BottomRight => Lang.BottomRight;
    public string Branches => Lang.Branches;
    public string Builds => Lang.Builds;
    public string Commits => Lang.Commits;
    public string CrossFade => Lang.CrossFade;
    public string CurrentPageData => Lang.CurrentPageData;
    public string CustomCanvas => Lang.CustomCanvas;
    public string Dashboards => Lang.Dashboards;
    public string Desktop => Lang.Desktop;
    public string EffectsComingSoon => Lang.EffectsComingSoon;
    public string Files => Lang.Files;
    public string Fireworks => Lang.Fireworks;
    public string First => Lang.First;
    public string GitHub => Lang.GitHub;
    public string Good => Lang.Good;
    public string HatchBrushGeneratorComingSoon => Lang.HatchBrushGeneratorComingSoon;
    public string Header => Lang.Header;
    public string HelloSenderBubble => Lang.HelloSenderBubble;
    public string HiReceiverBubble => Lang.HiReceiverBubble;
    public string Library => Lang.Library;
    public string LoadTest => Lang.LoadTest;
    public string More => Lang.More;
    public string MorphingAnimationComingSoon => Lang.MorphingAnimationComingSoon;
    public string NoMessagesYet => Lang.NoMessagesYet;
    public string NuGet => Lang.NuGet;
    public string Overview => Lang.Overview;
    public string Pipelines => Lang.Pipelines;
    public string PullRequests => Lang.PullRequests;
    public string Queries => Lang.Queries;
    public string RandomDirection => Lang.RandomDirection;
    public string RealisticLook => Lang.RealisticLook;
    public string Releases => Lang.Releases;
    public string RepeatButtonCustom => Lang.RepeatButtonCustom;
    public string Repos => Lang.Repos;
    public string Retry => Lang.Retry;
    public string RibbonAlignLeft => Lang.RibbonAlignLeft;
    public string RibbonAlignRight => Lang.RibbonAlignRight;
    public string RibbonBold => Lang.RibbonBold;
    public string RibbonCenter => Lang.RibbonCenter;
    public string RibbonChart => Lang.RibbonChart;
    public string RibbonClipboard => Lang.RibbonClipboard;
    public string RibbonCopy => Lang.RibbonCopy;
    public string RibbonCut => Lang.RibbonCut;
    public string RibbonDropCap => Lang.RibbonDropCap;
    public string RibbonFont => Lang.RibbonFont;
    public string RibbonFontSettings => Lang.RibbonFontSettings;
    public string RibbonGridlines => Lang.RibbonGridlines;
    public string RibbonIllustrations => Lang.RibbonIllustrations;
    public string RibbonInsert => Lang.RibbonInsert;
    public string RibbonItalic => Lang.RibbonItalic;
    public string RibbonNewWindow => Lang.RibbonNewWindow;
    public string RibbonParagraph => Lang.RibbonParagraph;
    public string RibbonPaste => Lang.RibbonPaste;
    public string RibbonPicture => Lang.RibbonPicture;
    public string RibbonRuler => Lang.RibbonRuler;
    public string RibbonShape => Lang.RibbonShape;
    public string RibbonShow => Lang.RibbonShow;
    public string RibbonStart => Lang.RibbonStart;
    public string RibbonSwitchWindow => Lang.RibbonSwitchWindow;
    public string RibbonText => Lang.RibbonText;
    public string RibbonTextBox => Lang.RibbonTextBox;
    public string RibbonUnderline => Lang.RibbonUnderline;
    public string RibbonView => Lang.RibbonView;
    public string RibbonWindow => Lang.RibbonWindow;
    public string RibbonWordArt => Lang.RibbonWordArt;
    public string Runs => Lang.Runs;
    public string SchoolPride => Lang.SchoolPride;
    public string SelectAll => Lang.SelectAll;
    public string SenderAudioMessage => Lang.SenderAudioMessage;
    public string ShowImageBrowser => Lang.ShowImageBrowser;
    public string ShowSprite => Lang.ShowSprite;
    public string SlideHorizontal => Lang.SlideHorizontal;
    public string SlideVertical => Lang.SlideVertical;
    public string Snow => Lang.Snow;
    public string Sprints => Lang.Sprints;
    public string Stars => Lang.Stars;
    public string Summary => Lang.Summary;
    public string Tags => Lang.Tags;
    public string TaskGroups => Lang.TaskGroups;
    public string TestPlans => Lang.TestPlans;
    public string TextText => Lang.TextText;
    public string TextTextText => Lang.TextTextText;
    public string TextTextTextText => Lang.TextTextTextText;
    public string TextTextTextTextText => Lang.TextTextTextTextText;
    public string ThisIsTheContent => Lang.ThisIsTheContent;
    public string TitlePlaceholder => Lang.TitlePlaceholder;
    public string TopLeft => Lang.TopLeft;
    public string TopRight => Lang.TopRight;
    public string Wiki => Lang.Wiki;
    public string WorkItems => Lang.WorkItems;


    public string this[string key] => GetLang(key);

    private void UpdateLangs()
    {
        OnPropertyChanged(string.Empty);
    }

    public event PropertyChangedEventHandler? PropertyChanged;

    protected virtual void OnPropertyChanged(string propertyName) =>
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
}



