using System.ComponentModel;
using System.Globalization;

namespace HandyControlDemo.Properties.Langs;

public class LangProvider : INotifyPropertyChanged
{
    private static readonly LangProvider InstanceField = new();

    public static LangProvider Instance => InstanceField;

    public static CultureInfo Culture
    {
        get => Lang.Culture;
        set
        {
            if (value == null || Equals(Lang.Culture, value))
            {
                return;
            }

            Lang.Culture = value;
            Instance.UpdateLangs();
        }
    }

    public static string GetLang(string key) =>
        Lang.ResourceManager.GetString(key, Lang.Culture) ?? key;

    public string About => Lang.About;
    public string AddItem => Lang.AddItem;
    public string AnimationPath => Lang.AnimationPath;
    public string AppClosingTip => Lang.AppClosingTip;
    public string Ask => Lang.Ask;
    public string AutoCompleteBox => Lang.AutoCompleteBox;
    public string Badge => Lang.Badge;
    public string BasicInfo => Lang.BasicInfo;
    public string BasicLayout => Lang.BasicLayout;
    public string Blink => Lang.Blink;
    public string Blog => Lang.Blog;
    public string Border => Lang.Border;
    public string Brush => Lang.Brush;
    public string Button => Lang.Button;
    public string ButtonCustom => Lang.ButtonCustom;
    public string ButtonGroup => Lang.ButtonGroup;
public string Calendar => Lang.Calendar;
    public string CalendarDatePicker => Lang.CalendarDatePicker;
    public string CalendarWithClock => Lang.CalendarWithClock;
    public string Card => Lang.Card;
    public string Carousel => Lang.Carousel;
    public string ChangeLangAsk => Lang.ChangeLangAsk;
    public string ChatBubble => Lang.ChatBubble;
    public string Chatroom => Lang.Chatroom;
    public string CheckBox => Lang.CheckBox;
    public string CheckComboBox => Lang.CheckComboBox;
    public string CirclePanel => Lang.CirclePanel;
    public string Clear => Lang.Clear;
    public string ConfettiCannon => Lang.ConfettiCannon;
    public string Content => Lang.Content;
    public string Click2Count => Lang.Click2Count;
    public string Clock => Lang.Clock;
    public string CloseMainWindowDialog => Lang.CloseMainWindowDialog;
    public string ColorPicker => Lang.ColorPicker;
    public string ColumnOffset => Lang.ColumnOffset;
    public string ColumnSpacing => Lang.ColumnSpacing;
    public string ComboBox => Lang.ComboBox;
    public string ComingSoon => Lang.ComingSoon;
    public string Comment => Lang.Comment;
    public string Common => Lang.Common;
    public string CompareSlider => Lang.CompareSlider;
    public string Complete => Lang.Complete;
    public string ContentDemoStr => Lang.ContentDemoStr;
    public string Contributors => Lang.Contributors;
    public string Controls => Lang.Controls;
    public string CoverFlow => Lang.CoverFlow;
    public string CoverView => Lang.CoverView;
    public string Danger => Lang.Danger;
    public string DataDisplay => Lang.DataDisplay;
    public string DataEntry => Lang.DataEntry;
    public string DataGrid => Lang.DataGrid;
    public string DatePicker => Lang.DatePicker;
    public string DateTimePicker => Lang.DateTimePicker;
    public string Default => Lang.Default;
    public string Demo => Lang.Demo;
    public string Dialog => Lang.Dialog;
    public string DialogDemo => Lang.DialogDemo;
    public string Divider => Lang.Divider;
    public string Doc_cn => Lang.Doc_cn;
    public string Doc_en => Lang.Doc_en;
public string Documentation => Lang.Documentation;
    public string DragHere => Lang.DragHere;
    public string Drawer => Lang.Drawer;
    public string DropDownButton => Lang.DropDownButton;
    public string Effects => Lang.Effects;
    public string ElementGroup => Lang.ElementGroup;
    public string Email => Lang.Email;
    public string Empty => Lang.Empty;
    public string Error => Lang.Error;
    public string Exit => Lang.Exit;
    public string Expander => Lang.Expander;
    public string Fatal => Lang.Fatal;
    public string Feedback => Lang.Feedback;
    public string FlexPanel => Lang.FlexPanel;
    public string FlipClock => Lang.FlipClock;
    public string FloatingBlock => Lang.FloatingBlock;
    public string FlowDocument => Lang.FlowDocument;
    public string FlowDocumentPageViewer => Lang.FlowDocumentPageViewer;
    public string FlowDocumentReader => Lang.FlowDocumentReader;
    public string FlowDocumentScrollViewer => Lang.FlowDocumentScrollViewer;
    public string Frame => Lang.Frame;
    public string Geometry => Lang.Geometry;
    public string GifImage => Lang.GifImage;
    public string GotoTop => Lang.GotoTop;
    public string Gravatar => Lang.Gravatar;
    public string Grid => Lang.Grid;
    public string GroupBox => Lang.GroupBox;
    public string Groups => Lang.Groups;
    public string Growl => Lang.Growl;
    public string GrowlAsk => Lang.GrowlAsk;
    public string GrowlDemo => Lang.GrowlDemo;
    public string GrowlError => Lang.GrowlError;
    public string GrowlFatal => Lang.GrowlFatal;
    public string GrowlInfo => Lang.GrowlInfo;
    public string GrowlSuccess => Lang.GrowlSuccess;
    public string GrowlWarning => Lang.GrowlWarning;
    public string HatchBrushGenerator => Lang.HatchBrushGenerator;
    public string HandyControl => Lang.HandyControl;
    public string HoneycombPanel => Lang.HoneycombPanel;
    public string HybridLayout => Lang.HybridLayout;
    public string HyperlinkButton => Lang.HyperlinkButton;
    public string Ignore => Lang.Ignore;
    public string ImageBlock => Lang.ImageBlock;
    public string ImageBrowser => Lang.ImageBrowser;
    public string ImageSelector => Lang.ImageSelector;
    public string ImageViewer => Lang.ImageViewer;
    public string Index => Lang.Index;
    public string Info => Lang.Info;
    public string Interacting => Lang.Interacting;
    public string InteractiveDialog => Lang.InteractiveDialog;
    public string IsNotPhone => Lang.IsNotPhone;
    public string Item1 => Lang.Item1;
    public string Item2 => Lang.Item2;
    public string Item3 => Lang.Item3;
    public string Label => Lang.Label;
    public string LangComment => Lang.LangComment;
    public string Layout => Lang.Layout;
    public string ListBox => Lang.ListBox;
    public string ListView => Lang.ListView;
    public string Loading => Lang.Loading;
    public string Magnifier => Lang.Magnifier;
public string Menu => Lang.Menu;
    public string MessageBox => Lang.MessageBox;
    public string MaskedTextBox => Lang.MaskedTextBox;
    public string Misc => Lang.Misc;
    public string MorphingAnimation => Lang.MorphingAnimation;
public string Name => Lang.Name;
    public string Navigation => Lang.Navigation;
    public string NoData => Lang.NoData;
    public string New => Lang.New;
    public string NewWindow => Lang.NewWindow;
    public string Next => Lang.Next;
    public string NextWeek => Lang.NextWeek;
    public string Notification => Lang.Notification;
    public string NotifyIcon => Lang.NotifyIcon;
    public string NumericUpDown => Lang.NumericUpDown;
    public string Off => Lang.Off;
    public string Ok => Lang.Ok;
    public string On => Lang.On;
    public string OpenBlurWindow => Lang.OpenBlurWindow;
    public string OpenCommonWindow => Lang.OpenCommonWindow;
    public string OpenCustomContentWindow => Lang.OpenCustomContentWindow;
    public string OpenCustomMessageWindow => Lang.OpenCustomMessageWindow;
    public string OpenCustomTitleBarWindow => Lang.OpenCustomTitleBarWindow;
    public string OpenGlowWindow => Lang.OpenGlowWindow;
    public string OpenImageBrowser => Lang.OpenImageBrowser;
    public string OpenMessageWindow => Lang.OpenMessageWindow;
    public string OpenMouseFollowWindow => Lang.OpenMouseFollowWindow;
    public string OpenNativeCommonWindow => Lang.OpenNativeCommonWindow;
    public string OpenNavigationWindow => Lang.OpenNavigationWindow;
    public string OpenNoCustomTitleBarDragableWindow => Lang.OpenNoCustomTitleBarDragableWindow;
    public string OpenPanel => Lang.OpenPanel;
    public string OpenSprite => Lang.OpenSprite;
    public string OpenTouchDragMoveWindow => Lang.OpenTouchDragMoveWindow;
    public string OptionA => Lang.OptionA;
    public string OptionB => Lang.OptionB;
    public string OutlineText => Lang.OutlineText;
    public string Pagination => Lang.Pagination;
    public string PasswordBox => Lang.PasswordBox;
    public string PinBox => Lang.PinBox;
    public string PleaseInput => Lang.PleaseInput;
    public string PleaseWait => Lang.PleaseWait;
    public string PlsEnterContent => Lang.PlsEnterContent;
    public string PlsEnterEmail => Lang.PlsEnterEmail;
    public string PlsEnterKey => Lang.PlsEnterKey;
    public string Poptip => Lang.Poptip;
    public string PoptipPositionStr => Lang.PoptipPositionStr;
    public string PracticalDemos => Lang.PracticalDemos;
    public string Prev => Lang.Prev;
    public string PreviewSlider => Lang.PreviewSlider;
    public string Primary => Lang.Primary;
    public string ProgressBar => Lang.ProgressBar;
    public string ProgressButton => Lang.ProgressButton;
    public string Project => Lang.Project;
    public string PropertyGrid => Lang.PropertyGrid;
    public string PushToTalk => Lang.PushToTalk;
    public string QQGroup => Lang.QQGroup;
    public string RadioButton => Lang.RadioButton;
    public string RangeSlider => Lang.RangeSlider;
public string Rate => Lang.Rate;
    public string Recommendation => Lang.Recommendation;
    public string Register => Lang.Register;
    public string RelativePanel => Lang.RelativePanel;
    public string Remark => Lang.Remark;
    public string RemoveItem => Lang.RemoveItem;
    public string RepeatButton => Lang.RepeatButton;
    public string Reply => Lang.Reply;
    public string Repository => Lang.Repository;
    public string ResponsiveLayout => Lang.ResponsiveLayout;
    public string Ribbon => Lang.Ribbon;
    public string RichTextBox => Lang.RichTextBox;
    public string RightClickHere => Lang.RightClickHere;
    public string RunningBlock => Lang.RunningBlock;
    public string Screenshot => Lang.Screenshot;
    public string ScrollViewer => Lang.ScrollViewer;
    public string SearchBar => Lang.SearchBar;
    public string Second => Lang.Second;
    public string Selected => Lang.Selected;
    public string SendNotification => Lang.SendNotification;
    public string Shield => Lang.Shield;
    public string ShowInCurrentWindow => Lang.ShowInCurrentWindow;
    public string ShowInMainWindow => Lang.ShowInMainWindow;
    public string ShowRowNumber => Lang.ShowRowNumber;
public string SideMenu => Lang.SideMenu;
    public string Slider => Lang.Slider;
    public string Small => Lang.Small;
    public string SplitButton => Lang.SplitButton;
    public string Sprite => Lang.Sprite;
    public string StartScreenshot => Lang.StartScreenshot;
    public string StaysOpen => Lang.StaysOpen;
    public string Step => Lang.Step;
    public string StepBar => Lang.StepBar;
    public string Styles => Lang.Styles;
    public string SubTitle => Lang.SubTitle;
    public string Success => Lang.Success;
    public string Switch => Lang.Switch;
    public string TabControl => Lang.TabControl;
    public string Tag => Lang.Tag;
    public string Text => Lang.Text;
    public string TextBlock => Lang.TextBlock;
    public string TextBox => Lang.TextBox;
    public string TextDialog => Lang.TextDialog;
    public string TextDialogInControl => Lang.TextDialogInControl;
    public string TextDialogWithTimer => Lang.TextDialogWithTimer;
    public string TimeBar => Lang.TimeBar;
    public string SelectedTime => Lang.SelectedTime;
    public string MouseWheelTip => Lang.MouseWheelTip;
    public string TimePicker => Lang.TimePicker;
    public string Tip => Lang.Tip;
    public string Title => Lang.Title;
    public string TitleDemoStr1 => Lang.TitleDemoStr1;
    public string TitleDemoStr2 => Lang.TitleDemoStr2;
    public string TitleDemoStr3 => Lang.TitleDemoStr3;
    public string Today => Lang.Today;
    public string ToggleButton => Lang.ToggleButton;
    public string ToggleSwitch => Lang.ToggleSwitch;
    public string Tomorrow => Lang.Tomorrow;
    public string ToolBar => Lang.ToolBar;
    public string Tools => Lang.Tools;
    public string Transfer => Lang.Transfer;
    public string TransitioningContentControl => Lang.TransitioningContentControl;
    public string TreeView => Lang.TreeView;
    public string Try2CloseApp => Lang.Try2CloseApp;
    public string Type => Lang.Type;
    public string UniformSpacingPanel => Lang.UniformSpacingPanel;
    public string UploadFile => Lang.UploadFile;
    public string UploadStr => Lang.UploadStr;
    public string Visibility => Lang.Visibility;
    public string Vsix => Lang.Vsix;
    public string Warning => Lang.Warning;
public string WaterfallPanel => Lang.WaterfallPanel;
    public string Watermark => Lang.Watermark;
    public string Website => Lang.Website;
    public string Window => Lang.Window;
    public string Close => Lang.Close;
    public string CustomTitleBarWindow => Lang.CustomTitleBarWindow;
    public string DragMe => Lang.DragMe;
    public string NotificationCardText => Lang.NotificationCardText;

    public string AddItem2 => Lang.AddItem2;
    public string AnotherSenderMessage => Lang.AnotherSenderMessage;
    public string Backlogs => Lang.Backlogs;
    public string BasicCannon => Lang.BasicCannon;
    public string Boards => Lang.Boards;
    public string BottomLeft => Lang.BottomLeft;
    public string BottomRight => Lang.BottomRight;
    public string Branches => Lang.Branches;
    public string Builds => Lang.Builds;
    public string Commits => Lang.Commits;
    public string CrossFade => Lang.CrossFade;
    public string CurrentPageData => Lang.CurrentPageData;
    public string CustomCanvas => Lang.CustomCanvas;
    public string Dashboards => Lang.Dashboards;
    public string Desktop => Lang.Desktop;
    public string EffectsComingSoon => Lang.EffectsComingSoon;
    public string Files => Lang.Files;
    public string Fireworks => Lang.Fireworks;
    public string First => Lang.First;
    public string GitHub => Lang.GitHub;
    public string Good => Lang.Good;
    public string HatchBrushGeneratorComingSoon => Lang.HatchBrushGeneratorComingSoon;
    public string Header => Lang.Header;
    public string HelloSenderBubble => Lang.HelloSenderBubble;
    public string HiReceiverBubble => Lang.HiReceiverBubble;
    public string Library => Lang.Library;
    public string LoadTest => Lang.LoadTest;
    public string More => Lang.More;
    public string MorphingAnimationComingSoon => Lang.MorphingAnimationComingSoon;
    public string NoMessagesYet => Lang.NoMessagesYet;
    public string NuGet => Lang.NuGet;
    public string Overview => Lang.Overview;
    public string Pipelines => Lang.Pipelines;
    public string PullRequests => Lang.PullRequests;
    public string Queries => Lang.Queries;
    public string RandomDirection => Lang.RandomDirection;
    public string RealisticLook => Lang.RealisticLook;
    public string Releases => Lang.Releases;
    public string RepeatButtonCustom => Lang.RepeatButtonCustom;
    public string Repos => Lang.Repos;
    public string Retry => Lang.Retry;
    public string RibbonAlignLeft => Lang.RibbonAlignLeft;
    public string RibbonAlignRight => Lang.RibbonAlignRight;
    public string RibbonBold => Lang.RibbonBold;
    public string RibbonCenter => Lang.RibbonCenter;
    public string RibbonChart => Lang.RibbonChart;
    public string RibbonClipboard => Lang.RibbonClipboard;
    public string RibbonCopy => Lang.RibbonCopy;
    public string RibbonCut => Lang.RibbonCut;
    public string RibbonDropCap => Lang.RibbonDropCap;
    public string RibbonFont => Lang.RibbonFont;
    public string RibbonFontSettings => Lang.RibbonFontSettings;
    public string RibbonGridlines => Lang.RibbonGridlines;
    public string RibbonIllustrations => Lang.RibbonIllustrations;
    public string RibbonInsert => Lang.RibbonInsert;
    public string RibbonItalic => Lang.RibbonItalic;
    public string RibbonNewWindow => Lang.RibbonNewWindow;
    public string RibbonParagraph => Lang.RibbonParagraph;
    public string RibbonPaste => Lang.RibbonPaste;
    public string RibbonPicture => Lang.RibbonPicture;
    public string RibbonRuler => Lang.RibbonRuler;
    public string RibbonShape => Lang.RibbonShape;
    public string RibbonShow => Lang.RibbonShow;
    public string RibbonStart => Lang.RibbonStart;
    public string RibbonSwitchWindow => Lang.RibbonSwitchWindow;
    public string RibbonText => Lang.RibbonText;
    public string RibbonTextBox => Lang.RibbonTextBox;
    public string RibbonUnderline => Lang.RibbonUnderline;
    public string RibbonView => Lang.RibbonView;
    public string RibbonWindow => Lang.RibbonWindow;
    public string RibbonWordArt => Lang.RibbonWordArt;
    public string Runs => Lang.Runs;
    public string SchoolPride => Lang.SchoolPride;
    public string SelectAll => Lang.SelectAll;
    public string SenderAudioMessage => Lang.SenderAudioMessage;
    public string ShowImageBrowser => Lang.ShowImageBrowser;
    public string ShowSprite => Lang.ShowSprite;
    public string SlideHorizontal => Lang.SlideHorizontal;
    public string SlideVertical => Lang.SlideVertical;
    public string Snow => Lang.Snow;
    public string Sprints => Lang.Sprints;
    public string Stars => Lang.Stars;
    public string Summary => Lang.Summary;
    public string Tags => Lang.Tags;
    public string TaskGroups => Lang.TaskGroups;
    public string TestPlans => Lang.TestPlans;
    public string TextText => Lang.TextText;
    public string TextTextText => Lang.TextTextText;
    public string TextTextTextText => Lang.TextTextTextText;
    public string TextTextTextTextText => Lang.TextTextTextTextText;
    public string ThisIsTheContent => Lang.ThisIsTheContent;
    public string TitlePlaceholder => Lang.TitlePlaceholder;
    public string TopLeft => Lang.TopLeft;
    public string TopRight => Lang.TopRight;
    public string Wiki => Lang.Wiki;
    public string WorkItems => Lang.WorkItems;


    public string this[string key] => GetLang(key);

    private void UpdateLangs()
    {
        OnPropertyChanged(nameof(About));
        OnPropertyChanged(nameof(AddItem));
        OnPropertyChanged(nameof(AnimationPath));
        OnPropertyChanged(nameof(AppClosingTip));
        OnPropertyChanged(nameof(Ask));
        OnPropertyChanged(nameof(AutoCompleteBox));
        OnPropertyChanged(nameof(Badge));
        OnPropertyChanged(nameof(BasicInfo));
        OnPropertyChanged(nameof(BasicLayout));
        OnPropertyChanged(nameof(Blink));
        OnPropertyChanged(nameof(Blog));
        OnPropertyChanged(nameof(Border));
        OnPropertyChanged(nameof(Brush));
        OnPropertyChanged(nameof(Button));
        OnPropertyChanged(nameof(ButtonCustom));
        OnPropertyChanged(nameof(ButtonGroup));
OnPropertyChanged(nameof(Calendar));
        OnPropertyChanged(nameof(CalendarDatePicker));
        OnPropertyChanged(nameof(CalendarWithClock));
        OnPropertyChanged(nameof(Card));
        OnPropertyChanged(nameof(Carousel));
        OnPropertyChanged(nameof(ChangeLangAsk));
        OnPropertyChanged(nameof(ChatBubble));
        OnPropertyChanged(nameof(Chatroom));
        OnPropertyChanged(nameof(CheckBox));
        OnPropertyChanged(nameof(CheckComboBox));
        OnPropertyChanged(nameof(CirclePanel));
        OnPropertyChanged(nameof(Clear));
        OnPropertyChanged(nameof(Click2Count));
        OnPropertyChanged(nameof(Clock));
        OnPropertyChanged(nameof(CloseMainWindowDialog));
        OnPropertyChanged(nameof(ColorPicker));
        OnPropertyChanged(nameof(ColumnOffset));
        OnPropertyChanged(nameof(ColumnSpacing));
        OnPropertyChanged(nameof(ComboBox));
        OnPropertyChanged(nameof(ComingSoon));
        OnPropertyChanged(nameof(Comment));
        OnPropertyChanged(nameof(Common));
        OnPropertyChanged(nameof(CompareSlider));
        OnPropertyChanged(nameof(Complete));
        OnPropertyChanged(nameof(ConfettiCannon));
        OnPropertyChanged(nameof(Content));
        OnPropertyChanged(nameof(ContentDemoStr));
        OnPropertyChanged(nameof(Contributors));
        OnPropertyChanged(nameof(Controls));
        OnPropertyChanged(nameof(CoverFlow));
        OnPropertyChanged(nameof(CoverView));
        OnPropertyChanged(nameof(Danger));
        OnPropertyChanged(nameof(DataDisplay));
        OnPropertyChanged(nameof(DataEntry));
        OnPropertyChanged(nameof(DataGrid));
        OnPropertyChanged(nameof(DatePicker));
        OnPropertyChanged(nameof(DateTimePicker));
        OnPropertyChanged(nameof(Default));
        OnPropertyChanged(nameof(Demo));
        OnPropertyChanged(nameof(Dialog));
        OnPropertyChanged(nameof(DialogDemo));
        OnPropertyChanged(nameof(Divider));
        OnPropertyChanged(nameof(Doc_cn));
        OnPropertyChanged(nameof(Doc_en));
OnPropertyChanged(nameof(Documentation));
        OnPropertyChanged(nameof(DragHere));
        OnPropertyChanged(nameof(Drawer));
        OnPropertyChanged(nameof(DropDownButton));
        OnPropertyChanged(nameof(Effects));
        OnPropertyChanged(nameof(ElementGroup));
        OnPropertyChanged(nameof(Email));
        OnPropertyChanged(nameof(Empty));
        OnPropertyChanged(nameof(Error));
        OnPropertyChanged(nameof(Exit));
        OnPropertyChanged(nameof(Expander));
        OnPropertyChanged(nameof(Fatal));
        OnPropertyChanged(nameof(Feedback));
        OnPropertyChanged(nameof(FlexPanel));
        OnPropertyChanged(nameof(FlipClock));
        OnPropertyChanged(nameof(FloatingBlock));
        OnPropertyChanged(nameof(FlowDocument));
        OnPropertyChanged(nameof(FlowDocumentPageViewer));
        OnPropertyChanged(nameof(FlowDocumentReader));
        OnPropertyChanged(nameof(FlowDocumentScrollViewer));
        OnPropertyChanged(nameof(Frame));
        OnPropertyChanged(nameof(Geometry));
        OnPropertyChanged(nameof(GifImage));
        OnPropertyChanged(nameof(GotoTop));
        OnPropertyChanged(nameof(Gravatar));
        OnPropertyChanged(nameof(Grid));
        OnPropertyChanged(nameof(GroupBox));
        OnPropertyChanged(nameof(Groups));
        OnPropertyChanged(nameof(Growl));
        OnPropertyChanged(nameof(GrowlAsk));
        OnPropertyChanged(nameof(GrowlDemo));
        OnPropertyChanged(nameof(GrowlError));
        OnPropertyChanged(nameof(GrowlFatal));
        OnPropertyChanged(nameof(GrowlInfo));
        OnPropertyChanged(nameof(GrowlSuccess));
        OnPropertyChanged(nameof(GrowlWarning));
OnPropertyChanged(nameof(HatchBrushGenerator));
        OnPropertyChanged(nameof(HandyControl));
        OnPropertyChanged(nameof(HoneycombPanel));
        OnPropertyChanged(nameof(HybridLayout));
        OnPropertyChanged(nameof(HyperlinkButton));
        OnPropertyChanged(nameof(Ignore));
        OnPropertyChanged(nameof(ImageBlock));
        OnPropertyChanged(nameof(ImageBrowser));
        OnPropertyChanged(nameof(ImageSelector));
        OnPropertyChanged(nameof(ImageViewer));
        OnPropertyChanged(nameof(Index));
        OnPropertyChanged(nameof(Info));
        OnPropertyChanged(nameof(Interacting));
        OnPropertyChanged(nameof(InteractiveDialog));
        OnPropertyChanged(nameof(IsNotPhone));
        OnPropertyChanged(nameof(Item1));
        OnPropertyChanged(nameof(Item2));
        OnPropertyChanged(nameof(Item3));
        OnPropertyChanged(nameof(Label));
        OnPropertyChanged(nameof(LangComment));
        OnPropertyChanged(nameof(Layout));
        OnPropertyChanged(nameof(ListBox));
        OnPropertyChanged(nameof(ListView));
        OnPropertyChanged(nameof(Loading));
OnPropertyChanged(nameof(Magnifier));
        OnPropertyChanged(nameof(MaskedTextBox));
        OnPropertyChanged(nameof(Menu));
        OnPropertyChanged(nameof(MessageBox));
        OnPropertyChanged(nameof(Misc));
        OnPropertyChanged(nameof(MorphingAnimation));
OnPropertyChanged(nameof(Name));
        OnPropertyChanged(nameof(Navigation));
        OnPropertyChanged(nameof(NoData));
        OnPropertyChanged(nameof(New));
        OnPropertyChanged(nameof(NewWindow));
        OnPropertyChanged(nameof(Next));
        OnPropertyChanged(nameof(NextWeek));
        OnPropertyChanged(nameof(Notification));
        OnPropertyChanged(nameof(NotifyIcon));
        OnPropertyChanged(nameof(NumericUpDown));
        OnPropertyChanged(nameof(Off));
        OnPropertyChanged(nameof(Ok));
        OnPropertyChanged(nameof(On));
        OnPropertyChanged(nameof(OpenBlurWindow));
        OnPropertyChanged(nameof(OpenCommonWindow));
        OnPropertyChanged(nameof(OpenCustomContentWindow));
        OnPropertyChanged(nameof(OpenCustomMessageWindow));
        OnPropertyChanged(nameof(OpenCustomTitleBarWindow));
        OnPropertyChanged(nameof(OpenGlowWindow));
        OnPropertyChanged(nameof(OpenImageBrowser));
        OnPropertyChanged(nameof(OpenMessageWindow));
        OnPropertyChanged(nameof(OpenMouseFollowWindow));
        OnPropertyChanged(nameof(OpenNativeCommonWindow));
        OnPropertyChanged(nameof(OpenNavigationWindow));
        OnPropertyChanged(nameof(OpenNoCustomTitleBarDragableWindow));
        OnPropertyChanged(nameof(OpenPanel));
        OnPropertyChanged(nameof(OpenSprite));
        OnPropertyChanged(nameof(OpenTouchDragMoveWindow));
        OnPropertyChanged(nameof(OptionA));
        OnPropertyChanged(nameof(OptionB));
        OnPropertyChanged(nameof(OutlineText));
        OnPropertyChanged(nameof(Pagination));
        OnPropertyChanged(nameof(PasswordBox));
        OnPropertyChanged(nameof(PinBox));
        OnPropertyChanged(nameof(PleaseInput));
        OnPropertyChanged(nameof(PleaseWait));
        OnPropertyChanged(nameof(PlsEnterContent));
        OnPropertyChanged(nameof(PlsEnterEmail));
        OnPropertyChanged(nameof(PlsEnterKey));
        OnPropertyChanged(nameof(Poptip));
        OnPropertyChanged(nameof(PoptipPositionStr));
        OnPropertyChanged(nameof(PracticalDemos));
        OnPropertyChanged(nameof(Prev));
        OnPropertyChanged(nameof(PreviewSlider));
        OnPropertyChanged(nameof(Primary));
        OnPropertyChanged(nameof(ProgressBar));
        OnPropertyChanged(nameof(ProgressButton));
        OnPropertyChanged(nameof(Project));
        OnPropertyChanged(nameof(PropertyGrid));
        OnPropertyChanged(nameof(PushToTalk));
        OnPropertyChanged(nameof(QQGroup));
        OnPropertyChanged(nameof(RadioButton));
        OnPropertyChanged(nameof(RangeSlider));
        OnPropertyChanged(nameof(Rate));
        OnPropertyChanged(nameof(Recommendation));
        OnPropertyChanged(nameof(Register));
        OnPropertyChanged(nameof(RelativePanel));
        OnPropertyChanged(nameof(Remark));
        OnPropertyChanged(nameof(RemoveItem));
        OnPropertyChanged(nameof(RepeatButton));
        OnPropertyChanged(nameof(Reply));
        OnPropertyChanged(nameof(Repository));
OnPropertyChanged(nameof(ResponsiveLayout));
        OnPropertyChanged(nameof(Ribbon));
        OnPropertyChanged(nameof(RichTextBox));
        OnPropertyChanged(nameof(RightClickHere));
        OnPropertyChanged(nameof(RunningBlock));
        OnPropertyChanged(nameof(Screenshot));
        OnPropertyChanged(nameof(ScrollViewer));
        OnPropertyChanged(nameof(SearchBar));
        OnPropertyChanged(nameof(Second));
        OnPropertyChanged(nameof(Selected));
        OnPropertyChanged(nameof(SendNotification));
        OnPropertyChanged(nameof(Shield));
        OnPropertyChanged(nameof(ShowInCurrentWindow));
        OnPropertyChanged(nameof(ShowInMainWindow));
        OnPropertyChanged(nameof(ShowRowNumber));
        OnPropertyChanged(nameof(SideMenu));
        OnPropertyChanged(nameof(Slider));
        OnPropertyChanged(nameof(Small));
        OnPropertyChanged(nameof(SplitButton));
        OnPropertyChanged(nameof(Sprite));
        OnPropertyChanged(nameof(StartScreenshot));
        OnPropertyChanged(nameof(StaysOpen));
        OnPropertyChanged(nameof(Step));
        OnPropertyChanged(nameof(StepBar));
        OnPropertyChanged(nameof(Styles));
        OnPropertyChanged(nameof(SubTitle));
        OnPropertyChanged(nameof(Success));
        OnPropertyChanged(nameof(Switch));
        OnPropertyChanged(nameof(TabControl));
        OnPropertyChanged(nameof(Tag));
        OnPropertyChanged(nameof(Text));
        OnPropertyChanged(nameof(TextBlock));
        OnPropertyChanged(nameof(TextBox));
        OnPropertyChanged(nameof(TextDialog));
        OnPropertyChanged(nameof(TextDialogInControl));
        OnPropertyChanged(nameof(TextDialogWithTimer));
        OnPropertyChanged(nameof(TimeBar));
        OnPropertyChanged(nameof(SelectedTime));
        OnPropertyChanged(nameof(MouseWheelTip));
        OnPropertyChanged(nameof(TimePicker));
        OnPropertyChanged(nameof(Tip));
        OnPropertyChanged(nameof(Title));
        OnPropertyChanged(nameof(TitleDemoStr1));
        OnPropertyChanged(nameof(TitleDemoStr2));
        OnPropertyChanged(nameof(TitleDemoStr3));
            OnPropertyChanged(nameof(Today));
OnPropertyChanged(nameof(ToggleButton));
        OnPropertyChanged(nameof(ToggleSwitch));
        OnPropertyChanged(nameof(Tomorrow));
        OnPropertyChanged(nameof(ToolBar));
        OnPropertyChanged(nameof(Tools));
        OnPropertyChanged(nameof(Transfer));
        OnPropertyChanged(nameof(TransitioningContentControl));
        OnPropertyChanged(nameof(TreeView));
        OnPropertyChanged(nameof(Try2CloseApp));
        OnPropertyChanged(nameof(Type));
        OnPropertyChanged(nameof(UniformSpacingPanel));
        OnPropertyChanged(nameof(UploadFile));
        OnPropertyChanged(nameof(UploadStr));
        OnPropertyChanged(nameof(Visibility));
        OnPropertyChanged(nameof(Vsix));
        OnPropertyChanged(nameof(Warning));
        OnPropertyChanged(nameof(WaterfallPanel));
        OnPropertyChanged(nameof(Watermark));
OnPropertyChanged(nameof(Website));
        OnPropertyChanged(nameof(Window));
        OnPropertyChanged(nameof(AddItem2));
        OnPropertyChanged(nameof(AnotherSenderMessage));
        OnPropertyChanged(nameof(Backlogs));
        OnPropertyChanged(nameof(BasicCannon));
        OnPropertyChanged(nameof(Boards));
        OnPropertyChanged(nameof(BottomLeft));
        OnPropertyChanged(nameof(BottomRight));
        OnPropertyChanged(nameof(Branches));
        OnPropertyChanged(nameof(Builds));
        OnPropertyChanged(nameof(Commits));
        OnPropertyChanged(nameof(CrossFade));
        OnPropertyChanged(nameof(CurrentPageData));
        OnPropertyChanged(nameof(CustomCanvas));
        OnPropertyChanged(nameof(Dashboards));
        OnPropertyChanged(nameof(Desktop));
        OnPropertyChanged(nameof(EffectsComingSoon));
        OnPropertyChanged(nameof(Files));
        OnPropertyChanged(nameof(Fireworks));
        OnPropertyChanged(nameof(First));
        OnPropertyChanged(nameof(GitHub));
        OnPropertyChanged(nameof(Good));
        OnPropertyChanged(nameof(HatchBrushGeneratorComingSoon));
        OnPropertyChanged(nameof(Header));
        OnPropertyChanged(nameof(HelloSenderBubble));
        OnPropertyChanged(nameof(HiReceiverBubble));
        OnPropertyChanged(nameof(Library));
        OnPropertyChanged(nameof(LoadTest));
        OnPropertyChanged(nameof(More));
        OnPropertyChanged(nameof(MorphingAnimationComingSoon));
        OnPropertyChanged(nameof(NoMessagesYet));
        OnPropertyChanged(nameof(NuGet));
        OnPropertyChanged(nameof(Overview));
        OnPropertyChanged(nameof(Pipelines));
        OnPropertyChanged(nameof(PullRequests));
        OnPropertyChanged(nameof(Queries));
        OnPropertyChanged(nameof(RandomDirection));
        OnPropertyChanged(nameof(RealisticLook));
        OnPropertyChanged(nameof(Releases));
        OnPropertyChanged(nameof(RepeatButtonCustom));
        OnPropertyChanged(nameof(Repos));
        OnPropertyChanged(nameof(Retry));
        OnPropertyChanged(nameof(RibbonAlignLeft));
        OnPropertyChanged(nameof(RibbonAlignRight));
        OnPropertyChanged(nameof(RibbonBold));
        OnPropertyChanged(nameof(RibbonCenter));
        OnPropertyChanged(nameof(RibbonChart));
        OnPropertyChanged(nameof(RibbonClipboard));
        OnPropertyChanged(nameof(RibbonCopy));
        OnPropertyChanged(nameof(RibbonCut));
        OnPropertyChanged(nameof(RibbonDropCap));
        OnPropertyChanged(nameof(RibbonFont));
        OnPropertyChanged(nameof(RibbonFontSettings));
        OnPropertyChanged(nameof(RibbonGridlines));
        OnPropertyChanged(nameof(RibbonIllustrations));
        OnPropertyChanged(nameof(RibbonInsert));
        OnPropertyChanged(nameof(RibbonItalic));
        OnPropertyChanged(nameof(RibbonNewWindow));
        OnPropertyChanged(nameof(RibbonParagraph));
        OnPropertyChanged(nameof(RibbonPaste));
        OnPropertyChanged(nameof(RibbonPicture));
        OnPropertyChanged(nameof(RibbonRuler));
        OnPropertyChanged(nameof(RibbonShape));
        OnPropertyChanged(nameof(RibbonShow));
        OnPropertyChanged(nameof(RibbonStart));
        OnPropertyChanged(nameof(RibbonSwitchWindow));
        OnPropertyChanged(nameof(RibbonText));
        OnPropertyChanged(nameof(RibbonTextBox));
        OnPropertyChanged(nameof(RibbonUnderline));
        OnPropertyChanged(nameof(RibbonView));
        OnPropertyChanged(nameof(RibbonWindow));
        OnPropertyChanged(nameof(RibbonWordArt));
        OnPropertyChanged(nameof(Runs));
        OnPropertyChanged(nameof(SchoolPride));
        OnPropertyChanged(nameof(SelectAll));
        OnPropertyChanged(nameof(SenderAudioMessage));
        OnPropertyChanged(nameof(ShowImageBrowser));
        OnPropertyChanged(nameof(ShowSprite));
        OnPropertyChanged(nameof(SlideHorizontal));
        OnPropertyChanged(nameof(SlideVertical));
        OnPropertyChanged(nameof(Snow));
        OnPropertyChanged(nameof(Sprints));
        OnPropertyChanged(nameof(Stars));
        OnPropertyChanged(nameof(Summary));
        OnPropertyChanged(nameof(Tags));
        OnPropertyChanged(nameof(TaskGroups));
        OnPropertyChanged(nameof(TestPlans));
        OnPropertyChanged(nameof(TextText));
        OnPropertyChanged(nameof(TextTextText));
        OnPropertyChanged(nameof(TextTextTextText));
        OnPropertyChanged(nameof(TextTextTextTextText));
        OnPropertyChanged(nameof(ThisIsTheContent));
        OnPropertyChanged(nameof(TitlePlaceholder));
        OnPropertyChanged(nameof(TopLeft));
        OnPropertyChanged(nameof(TopRight));
        OnPropertyChanged(nameof(Wiki));
        OnPropertyChanged(nameof(WorkItems));

        OnPropertyChanged(nameof(Close));
        OnPropertyChanged(nameof(CustomTitleBarWindow));
        OnPropertyChanged(nameof(DragMe));
        OnPropertyChanged(nameof(NotificationCardText));

        OnPropertyChanged("Item[]");
    }

    public event PropertyChangedEventHandler? PropertyChanged;

    protected virtual void OnPropertyChanged(string propertyName) =>
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
}



